// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `native/include/bluez_obex_native.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class BluezObexNativeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BluezObexNativeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BluezObexNativeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Byte-returning functions allocate *out and return its length (or a negative
  /// status on failure). Call bluez_obex_free on successful results, including
  /// empty results. Each operation executes exactly once; there is no sizing call.
  void bluez_obex_free(ffi.Pointer<ffi.Void> buffer) {
    return _bluez_obex_free(buffer);
  }

  late final _bluez_obex_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_obex_free',
      );
  late final _bluez_obex_free = _bluez_obex_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// ── Client lifecycle ────────────────────────────────────────────────────────
  int bluez_obex_get_devices(ffi.Pointer<ffi.Pointer<ffi.Uint8>> out) {
    return _bluez_obex_get_devices(out);
  }

  late final _bluez_obex_get_devicesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>)
        >
      >('bluez_obex_get_devices');
  late final _bluez_obex_get_devices = _bluez_obex_get_devicesPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>)>();

  void bluez_obex_init(ffi.Pointer<ffi.Void> dart_api_dl_data) {
    return _bluez_obex_init(dart_api_dl_data);
  }

  late final _bluez_obex_initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_obex_init',
      );
  late final _bluez_obex_init = _bluez_obex_initPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> bluez_obex_client_create(int events_port) {
    return _bluez_obex_client_create(events_port);
  }

  late final _bluez_obex_client_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Int64)>>(
        'bluez_obex_client_create',
      );
  late final _bluez_obex_client_create = _bluez_obex_client_createPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  void bluez_obex_client_destroy(ffi.Pointer<ffi.Void> handle) {
    return _bluez_obex_client_destroy(handle);
  }

  late final _bluez_obex_client_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'bluez_obex_client_destroy',
      );
  late final _bluez_obex_client_destroy = _bluez_obex_client_destroyPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// ── Session management ─────────────────────────────────────────────────────
  int bluez_obex_client_create_session(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> destination,
    ffi.Pointer<ffi.Char> target,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_client_create_session(handle, destination, target, out);
  }

  late final _bluez_obex_client_create_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_client_create_session');
  late final _bluez_obex_client_create_session =
      _bluez_obex_client_create_sessionPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_client_remove_session(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> session_path,
  ) {
    return _bluez_obex_client_remove_session(handle, session_path);
  }

  late final _bluez_obex_client_remove_sessionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_client_remove_session');
  late final _bluez_obex_client_remove_session =
      _bluez_obex_client_remove_sessionPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_obex_session_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> session_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_session_get_properties(handle, session_path, out);
  }

  late final _bluez_obex_session_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_session_get_properties');
  late final _bluez_obex_session_get_properties =
      _bluez_obex_session_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_session_get_capabilities(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> session_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_session_get_capabilities(handle, session_path, out);
  }

  late final _bluez_obex_session_get_capabilitiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_session_get_capabilities');
  late final _bluez_obex_session_get_capabilities =
      _bluez_obex_session_get_capabilitiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  /// ── Transfer management ──────────────────────────────────────────────────
  int bluez_obex_transfer_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transfer_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_transfer_get_properties(handle, transfer_path, out);
  }

  late final _bluez_obex_transfer_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_transfer_get_properties');
  late final _bluez_obex_transfer_get_properties =
      _bluez_obex_transfer_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_transfer_cancel(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transfer_path,
  ) {
    return _bluez_obex_transfer_cancel(handle, transfer_path);
  }

  late final _bluez_obex_transfer_cancelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_transfer_cancel');
  late final _bluez_obex_transfer_cancel = _bluez_obex_transfer_cancelPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_obex_transfer_suspend(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transfer_path,
  ) {
    return _bluez_obex_transfer_suspend(handle, transfer_path);
  }

  late final _bluez_obex_transfer_suspendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_transfer_suspend');
  late final _bluez_obex_transfer_suspend = _bluez_obex_transfer_suspendPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_obex_transfer_resume(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> transfer_path,
  ) {
    return _bluez_obex_transfer_resume(handle, transfer_path);
  }

  late final _bluez_obex_transfer_resumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_transfer_resume');
  late final _bluez_obex_transfer_resume = _bluez_obex_transfer_resumePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  /// ── ObjectManager queries ──────────────────────────────────────────────────
  int bluez_obex_get_managed_objects(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_get_managed_objects(handle, out);
  }

  late final _bluez_obex_get_managed_objectsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_get_managed_objects');
  late final _bluez_obex_get_managed_objects =
      _bluez_obex_get_managed_objectsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  /// ── Phonebook Access Profile ───────────────────────────────────────────────
  int bluez_obex_phonebook_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_get_properties(handle, phonebook_path, out);
  }

  late final _bluez_obex_phonebook_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_get_properties');
  late final _bluez_obex_phonebook_get_properties =
      _bluez_obex_phonebook_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_phonebook_select(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Char> location,
    ffi.Pointer<ffi.Char> phonebook,
  ) {
    return _bluez_obex_phonebook_select(
      handle,
      phonebook_path,
      location,
      phonebook,
    );
  }

  late final _bluez_obex_phonebook_selectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_obex_phonebook_select');
  late final _bluez_obex_phonebook_select = _bluez_obex_phonebook_selectPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int bluez_obex_phonebook_pull_all(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Char> target_file,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_pull_all(
      handle,
      phonebook_path,
      target_file,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_phonebook_pull_allPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_pull_all');
  late final _bluez_obex_phonebook_pull_all = _bluez_obex_phonebook_pull_allPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int bluez_obex_phonebook_pull(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Char> vcard,
    ffi.Pointer<ffi.Char> target_file,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_pull(
      handle,
      phonebook_path,
      vcard,
      target_file,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_phonebook_pullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_pull');
  late final _bluez_obex_phonebook_pull = _bluez_obex_phonebook_pullPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int bluez_obex_phonebook_list(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_list(
      handle,
      phonebook_path,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_phonebook_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_list');
  late final _bluez_obex_phonebook_list = _bluez_obex_phonebook_listPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int bluez_obex_phonebook_search(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Char> field,
    ffi.Pointer<ffi.Char> value,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_search(
      handle,
      phonebook_path,
      field,
      value,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_phonebook_searchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_search');
  late final _bluez_obex_phonebook_search = _bluez_obex_phonebook_searchPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int bluez_obex_phonebook_get_size(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
  ) {
    return _bluez_obex_phonebook_get_size(handle, phonebook_path);
  }

  late final _bluez_obex_phonebook_get_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_phonebook_get_size');
  late final _bluez_obex_phonebook_get_size = _bluez_obex_phonebook_get_sizePtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>();

  int bluez_obex_phonebook_update_version(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
  ) {
    return _bluez_obex_phonebook_update_version(handle, phonebook_path);
  }

  late final _bluez_obex_phonebook_update_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_phonebook_update_version');
  late final _bluez_obex_phonebook_update_version =
      _bluez_obex_phonebook_update_versionPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_obex_phonebook_list_filter_fields(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> phonebook_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_phonebook_list_filter_fields(
      handle,
      phonebook_path,
      out,
    );
  }

  late final _bluez_obex_phonebook_list_filter_fieldsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_phonebook_list_filter_fields');
  late final _bluez_obex_phonebook_list_filter_fields =
      _bluez_obex_phonebook_list_filter_fieldsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  /// ── Message Access Profile ─────────────────────────────────────────────────
  int bluez_obex_message_access_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_access_get_properties(
      handle,
      message_access_path,
      out,
    );
  }

  late final _bluez_obex_message_access_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_access_get_properties');
  late final _bluez_obex_message_access_get_properties =
      _bluez_obex_message_access_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_access_set_folder(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Char> folder,
  ) {
    return _bluez_obex_message_access_set_folder(
      handle,
      message_access_path,
      folder,
    );
  }

  late final _bluez_obex_message_access_set_folderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('bluez_obex_message_access_set_folder');
  late final _bluez_obex_message_access_set_folder =
      _bluez_obex_message_access_set_folderPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  int bluez_obex_message_access_list_folders(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_access_list_folders(
      handle,
      message_access_path,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_message_access_list_foldersPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_access_list_folders');
  late final _bluez_obex_message_access_list_folders =
      _bluez_obex_message_access_list_foldersPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_access_list_filter_fields(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_access_list_filter_fields(
      handle,
      message_access_path,
      out,
    );
  }

  late final _bluez_obex_message_access_list_filter_fieldsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_access_list_filter_fields');
  late final _bluez_obex_message_access_list_filter_fields =
      _bluez_obex_message_access_list_filter_fieldsPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_access_list_messages(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Char> folder,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> filter_values,
    int filter_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_access_list_messages(
      handle,
      message_access_path,
      folder,
      filter_keys,
      filter_values,
      filter_count,
      out,
    );
  }

  late final _bluez_obex_message_access_list_messagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_access_list_messages');
  late final _bluez_obex_message_access_list_messages =
      _bluez_obex_message_access_list_messagesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_access_update_inbox(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
  ) {
    return _bluez_obex_message_access_update_inbox(handle, message_access_path);
  }

  late final _bluez_obex_message_access_update_inboxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
        >
      >('bluez_obex_message_access_update_inbox');
  late final _bluez_obex_message_access_update_inbox =
      _bluez_obex_message_access_update_inboxPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)
          >();

  int bluez_obex_message_access_push_message(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_access_path,
    ffi.Pointer<ffi.Char> source_file,
    ffi.Pointer<ffi.Char> folder,
    ffi.Pointer<ffi.Pointer<ffi.Char>> arg_keys,
    ffi.Pointer<ffi.Pointer<ffi.Char>> arg_values,
    int arg_count,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_access_push_message(
      handle,
      message_access_path,
      source_file,
      folder,
      arg_keys,
      arg_values,
      arg_count,
      out,
    );
  }

  late final _bluez_obex_message_access_push_messagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_access_push_message');
  late final _bluez_obex_message_access_push_message =
      _bluez_obex_message_access_push_messagePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              int,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_get_properties(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_path,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_get_properties(handle, message_path, out);
  }

  late final _bluez_obex_message_get_propertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_get_properties');
  late final _bluez_obex_message_get_properties =
      _bluez_obex_message_get_propertiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            )
          >();

  int bluez_obex_message_get(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_path,
    ffi.Pointer<ffi.Char> target_file,
    int attachment,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out,
  ) {
    return _bluez_obex_message_get(
      handle,
      message_path,
      target_file,
      attachment,
      out,
    );
  }

  late final _bluez_obex_message_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          )
        >
      >('bluez_obex_message_get');
  late final _bluez_obex_message_get = _bluez_obex_message_getPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        )
      >();

  int bluez_obex_message_set_read(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_path,
    int read,
  ) {
    return _bluez_obex_message_set_read(handle, message_path, read);
  }

  late final _bluez_obex_message_set_readPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('bluez_obex_message_set_read');
  late final _bluez_obex_message_set_read = _bluez_obex_message_set_readPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, int)
      >();

  int bluez_obex_message_set_deleted(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Char> message_path,
    int deleted,
  ) {
    return _bluez_obex_message_set_deleted(handle, message_path, deleted);
  }

  late final _bluez_obex_message_set_deletedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('bluez_obex_message_set_deleted');
  late final _bluez_obex_message_set_deleted =
      _bluez_obex_message_set_deletedPtr
          .asFunction<
            int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, int)
          >();
}
